version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - "/src/*"
      - "/tests/*"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      nuget-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
